# Generated by Django 5.2.18 on 2026-10-07 21:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delegaciones', '0001_initial'),
        ('vecinos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('certificado', 'Certificado'), ('permiso', 'Permiso'), ('reclamo', 'Reclamo'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(max_length=3000, verbose_name='descripción')),
                ('estado', models.CharField(choices=[('ingresada', 'Ingresada'), ('asignada', 'Asignada'), ('atencion', 'En atención'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada')], default='ingresada', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creadas', to=settings.AUTH_USER_MODEL)),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delegaciones.delegacion')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignadas', to=settings.AUTH_USER_MODEL)),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vecinos.vecino')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=2000)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones', to='solicitudes.solicitud')),
            ],
            options={
                'ordering': ['fecha', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CambioEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anterior', models.CharField(choices=[('ingresada', 'Ingresada'), ('asignada', 'Asignada'), ('atencion', 'En atención'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada')], max_length=20)),
                ('nuevo', models.CharField(choices=[('ingresada', 'Ingresada'), ('asignada', 'Asignada'), ('atencion', 'En atención'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada')], max_length=20)),
                ('motivo', models.TextField(max_length=2000)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios', to='solicitudes.solicitud')),
            ],
            options={
                'ordering': ['fecha', 'pk'],
            },
        ),
    ]
