# Generated by Django 5.2.18 on 2026-10-07 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delegaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=25, verbose_name='teléfono')),
                ('direccion', models.CharField(max_length=200, verbose_name='dirección')),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delegaciones.delegacion')),
            ],
            options={
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('delegacion', 'rut'), name='rut_por_delegacion')],
            },
        ),
    ]
